### ISSUE TITLE
Hello Nimo! 

### ISSUE THREAD

**Issue by dbarenholz** [nimobeeren/webtex#10]
:wave: Hi Nimo!

This project is absolutely bonkers; very cool. For inspiration on how you can go from markdown to a rendered html page I suggest you look at obsidian (https://obsidian.md) and its plethora of plugins! Maybe you can even copy-paste some functionality (almost) directly!

Feel free to close this issue; just wanted to mention obsidian.

**Comment by nimobeeren** [comment]
Hi Daniel :smiley: 

I've heard good things about obsidian, but haven't tried it myself. I'll check it out!

Any features you'd like to see in particular? I'll probably do tables as one of the next things.

**Comment by dbarenholz** [comment]
No features I'd like to see for now; I don't think I'll be using it much if at all since I'm so used to LaTeX & Overleaf itself. Still think it's wicked that you've made this though :D

**Comment by nimobeeren** [comment]
@dbarenholz okay, thanks for your feedback!
